In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
staar22_df = pd.read_csv('data/DATA_STAAR_DISTRICT_2022.csv')
staar21_df = pd.read_csv('data/DATA_STAAR_DISTRICT_2021.csv')
staar19_df = pd.read_csv('data/DATA_STAAR_DISTRICT_2019.csv')

In [8]:
staar22_df

,District #,r_all_d_g3_2022,r_ethh_d_g3_2022,r_etha_d_g3_2022,r_ethb_d_g3_2022,r_ethw_d_g3_2022,r_ecoy_d_g3_2022,r_eco1_d_g3_2022,r_ti1y_d_g3_2022,r_spey_d_g3_2022,...,r_spey_rs_g8_2022,m_all_rs_g8_2022,m_ethh_rs_g8_2022,m_etha_rs_g8_2022,m_ethb_rs_g8_2022,m_ethw_rs_g8_2022,m_ecoy_rs_g8_2022,m_eco1_rs_g8_2022,m_ti1y_rs_g8_2022,m_spey_rs_g8_2022
0,1902,40.0,6.0,0.0,0.0,32.0,22.0,20.0,40.0,8.0,...,1583.0,1751.0,1721.0,NaN,NaN,1761.0,1741.0,1745.0,1751.0,1589.0
1,1903,85.0,10.0,0.0,5.0,64.0,41.0,39.0,85.0,13.0,...,1562.0,1702.0,1686.0,NaN,NaN,1710.0,1656.0,1657.0,1703.0,1573.0
2,1904,61.0,7.0,1.0,4.0,48.0,32.0,32.0,61.0,8.0,...,1549.0,1639.0,1677.0,NaN,NaN,1628.0,1646.0,1642.0,1639.0,1553.0
3,1906,20.0,1.0,0.0,2.0,17.0,11.0,7.0,20.0,2.0,...,NaN,1785.0,NaN,NaN,NaN,1773.0,1736.0,1742.0,1785.0,NaN
4,1907,221.0,78.0,2.0,64.0,68.0,159.0,136.0,221.0,30.0,...,1572.0,1709.0,1702.0,NaN,1659.0,1740.0,1683.0,1676.0,1709.0,1542.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1180,72801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1181,72802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1474.0,1483.0,NaN,NaN,NaN,1474.0,NaN,1471.0,NaN
1182,227622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1183,111801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1184,183801,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1604.0,NaN,NaN,1597.0,1600.0,1573.0,NaN,NaN,NaN

In [9]:
staar21_df

,DNAME_g3_2021,r_all_rs_g3_2021,r_ti1y_rs_g3_2021,r_ecoy_rs_g3_2021,r_eco1_rs_g3_2021,r_etha_rs_g3_2021,r_ethh_rs_g3_2021,r_ethb_rs_g3_2021,r_ethw_rs_g3_2021,r_spey_rs_g3_2021,...,m_spey_rs_g8_2021,m_all_d_g8_2021,m_ti1y_d_g8_2021,m_ecoy_d_g8_2021,m_eco1_d_g8_2021,m_etha_d_g8_2021,m_ethh_d_g8_2021,m_ethb_d_g8_2021,m_ethw_d_g8_2021,m_spey_d_g8_2021
0,CAYUGA ISD,1523.0,1523.0,1486.0,1439.0,NaN,NaN,NaN,1543.0,NaN,...,NaN,37.0,37.0,13.0,10.0,0.0,6.0,0.0,29.0,3.0
1,ELKHART ISD,1463.0,1463.0,1416.0,1415.0,NaN,1444.0,NaN,1465.0,1352.0,...,1531.0,56.0,56.0,32.0,25.0,0.0,8.0,6.0,38.0,10.0
2,FRANKSTON ISD,1504.0,1504.0,1453.0,1453.0,NaN,1447.0,NaN,1507.0,1355.0,...,1594.0,38.0,38.0,26.0,23.0,1.0,7.0,6.0,22.0,7.0
3,NECHES ISD,1474.0,1474.0,1416.0,1393.0,NaN,NaN,NaN,1468.0,NaN,...,NaN,25.0,25.0,10.0,8.0,0.0,3.0,3.0,19.0,1.0
4,PALESTINE ISD,1401.0,1401.0,1382.0,1378.0,NaN,1411.0,1364.0,1425.0,1331.0,...,1573.0,259.0,258.0,186.0,157.0,3.0,126.0,53.0,69.0,31.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,8.0,6.0,6.0,5.0,0.0,1.0,0.0,5.0,0.0
3197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.0,4.0,4.0,4.0,0.0,2.0,0.0,3.0,0.0
3198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.0,7.0,7.0,7.0,0.0,4.0,4.0,3.0,2.0
3199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,33.0,5.0,9.0,1.0,0.0,2.0,0.0,28.0,2.0
3200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,0.0,2.0,2.0,0.0,1.0,0.0,2.0,2.0

In [5]:
staar19_df

,DNAME_g3_2019,r_all_d_g3_2019,r_ethh_d_g3_2019,r_etha_d_g3_2019,r_ethb_d_g3_2019,r_ethw_d_g3_2019,r_ecoy_d_g3_2019,r_eco1_d_g3_2019,r_ti1y_d_g3_2019,r_spey_d_g3_2019,...,m_spey_rs_g8_2019,m_all_d_g8_2019,m_ti1y_d_g8_2019,m_ecoy_d_g8_2019,m_eco1_d_g8_2019,m_etha_d_g8_2019,m_ethh_d_g8_2019,m_ethb_d_g8_2019,m_ethw_d_g8_2019,m_spey_d_g8_2019
0,CAYUGA ISD,46.0,3.0,0.0,3.0,38.0,23.0,17.0,46.0,7.0,...,NaN,41.0,41.0,13.0,8.0,1.0,3.0,0.0,34.0,4.0
1,ELKHART ISD,94.0,10.0,0.0,5.0,76.0,55.0,52.0,94.0,6.0,...,1576.0,80.0,80.0,46.0,41.0,0.0,8.0,6.0,64.0,8.0
2,ELKHART ISD,94.0,10.0,0.0,5.0,76.0,55.0,52.0,94.0,6.0,...,1576.0,80.0,80.0,46.0,41.0,0.0,8.0,6.0,64.0,8.0
3,FRANKSTON ISD,55.0,5.0,1.0,6.0,40.0,34.0,34.0,55.0,5.0,...,1608.0,42.0,42.0,23.0,21.0,0.0,3.0,7.0,29.0,11.0
4,NECHES ISD,25.0,5.0,0.0,2.0,16.0,10.0,10.0,25.0,2.0,...,NaN,29.0,29.0,13.0,9.0,0.0,3.0,1.0,24.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3305,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,11.0,9.0,8.0,5.0,0.0,3.0,0.0,6.0,2.0
3306,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,1.0,3.0,2.0,0.0,3.0,0.0,0.0,0.0
3307,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,0.0,4.0,4.0,0.0,1.0,1.0,2.0,4.0
3308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,5.0,4.0,3.0,2.0,0.0,1.0,0.0,4.0,3.0
3309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12.0,0.0,10.0,0.0,0.0,0.0,3.0,8.0,4.0